// Auto-generated from PHP enum: App\Enums\BasketItemType
// Do not edit this file manually

export const BasketItemType = {
    PRODUCT: 'product',
};

export const PRODUCT = 'product';

export default BasketItemType;