// Auto-generated from PHP enum: App\Enums\BasketType
// Do not edit this file manually

export const BasketType = {
    OPEN: 'open',
    CHECKED_OUT: 'checked_out',
    ABANDONED: 'abandoned',
};

export const OPEN = 'open';
export const CHECKED_OUT = 'checked_out';
export const ABANDONED = 'abandoned';

export default BasketType;