// Auto-generated from PHP enum: App\Enums\DeliveryType
// Do not edit this file manually

export const DeliveryType = {
    PICKUP: 'pickup',
    ADDRESS: 'address',
};

export const PICKUP = 'pickup';
export const ADDRESS = 'address';

export default DeliveryType;