// Auto-generated from PHP enum: App\Enums\Entity
// Do not edit this file manually

export const Entity = {
    PRODUCT: 'product',
    ARTICLE: 'article',
    USER: 'user',
    PAGE: 'page',
    BANNER: 'banner',
    BRAND: 'brand',
    MESSAGE: 'message',
    REGISTER: 'register',
    CUSTOMER: 'customer',
    TRANSPORT: 'transport',
    PAYMENT: 'payment',
    ATTRIBUTE: 'attribute',
};

export const PRODUCT = 'product';
export const ARTICLE = 'article';
export const USER = 'user';
export const PAGE = 'page';
export const BANNER = 'banner';
export const BRAND = 'brand';
export const MESSAGE = 'message';
export const REGISTER = 'register';
export const CUSTOMER = 'customer';
export const TRANSPORT = 'transport';
export const PAYMENT = 'payment';
export const ATTRIBUTE = 'attribute';

export default Entity;