// Auto-generated from PHP enum: App\Enums\PaymentType
// Do not edit this file manually

export const PaymentType = {
    COD: 'cod',
    CASH: 'cash',
    CARD: 'card',
    BANK: 'bank',
    BENEFIT_CARD: 'benefit_card',
};

export const COD = 'cod';
export const CASH = 'cash';
export const CARD = 'card';
export const BANK = 'bank';
export const BENEFIT_CARD = 'benefit_card';

export default PaymentType;