// Auto-generated from PHP enum: App\Enums\TransportType
// Do not edit this file manually

export const TransportType = {
    PERSONAL: 'personal',
    CP_NP: 'cp-np',
    CP_DR: 'cp-dr',
    CP_BA: 'cp-ba',
    PPL: 'ppl',
    PPL_PARCEL: 'ppl-parcel',
    DHL: 'dhl',
    PACKETA_CZ: 'packeta-cz',
    PACKETA_SK: 'packeta-sk',
    DPD: 'dpd',
    DPD_PICKUP: 'dpd-pickup',
};

export const PERSONAL = 'personal';
export const CP_NP = 'cp-np';
export const CP_DR = 'cp-dr';
export const CP_BA = 'cp-ba';
export const PPL = 'ppl';
export const PPL_PARCEL = 'ppl-parcel';
export const DHL = 'dhl';
export const PACKETA_CZ = 'packeta-cz';
export const PACKETA_SK = 'packeta-sk';
export const DPD = 'dpd';
export const DPD_PICKUP = 'dpd-pickup';

export default TransportType;